### ISSUE TITLE
BUG4c89: customSwitchConf解析问题

### ISSUE THREAD

**Issue by samueldeng** [samueldeng/interonet#26]
authToken` = [7616903071748199064548106023175668320], slice = [{"controllerConf": {"ip": "123.133.123.123", "port": "122"}, "num": {"vmsNum": "2", "switchesNum": "1"}, "switchConf": {"s0": "OF1.3"}, "topology": {"h0:0": "s0:1", "h1:0": "s0:3"}, "time": {"begin": "2016-05-03T19:01:53+08:00", "end": "2016-05-03T20:01:57+08:00"}}]
2016-05-03 18:02:19 ERROR GDMCore:185 - Submit Slice Error
java.lang.Exception: Parse Error: 'customSwitchConf' is null
    at org.interonet.gdm.Core.Slice$SliceParser.parse(Slice.java:318)
    at org.interonet.gdm.Core.GDMCore.submitSlice(GDMCore.java:179)
    at org.interonet.gdm.WebService.GDMServiceImpl.submitSlice(GDMServiceImpl.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:401)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:292)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:224)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:192)
    at com.googlecode.jsonrpc4j.JsonRpcServer.handle(JsonRpcServer.java:115)
    at org.interonet.gdm.WebService.RPCServlet.doPost(RPCServlet.java:25)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:801)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1126)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1060)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:509)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:288)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:240)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:539)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
2016-05-03 18:02:19 ERROR GDMServiceImpl:104 - submitSlice
java.lang.Exception: Parse Error: 'customSwitchConf' is null
    at org.interonet.gdm.Core.Slice$SliceParser.parse(Slice.java:318)
    at org.interonet.gdm.Core.GDMCore.submitSlice(GDMCore.java:179)
    at org.interonet.gdm.WebService.GDMServiceImpl.submitSlice(GDMServiceImpl.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:401)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:292)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:224)
    at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:192)
    at com.googlecode.jsonrpc4j.JsonRpcServer.handle(JsonRpcServer.java:115)
    at org.interonet.gdm.WebService.RPCServlet.doPost(RPCServlet.java:25)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:801)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1126)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1060)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:509)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:288)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:240)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:539)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
    at java.lang.Thread.run(Thread.java:745)
2016-05-03 18:06:03 WARN  HttpParser:1243 - bad HTTP parsed: 400 Illegal character 0x4 in state=START in '\x04<<<\x01\x00P_\xD5\xC3\xDb\x00>>>405 HTTP method G...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' for HttpChannelOverHttp@7ddc7ea8{r=0,c=false,a=IDLE,uri=-}
2016-05-03 18:06:16 WARN  HttpParser:1243 - bad HTTP parsed: 400 Illegal character 0x5 in state=START in '\x05<<<\x01\x00>>>P/1.1 400 Illegal...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' for HttpChannelOverHttp@6403bcbc{r=0,c=false,a=IDLE,uri=-}

**Comment by samueldeng** [comment]
[fix this.](https://github.com/samueldeng/interonet/commit/5a3a700dc3039d1fc85b8793fd3b0eb3e3e61a0c)
